Meteor rn reachability url pr
meteorrn/meteor-react-native pull request #120
Opened 2023-07-02 20:34 UTC by bratelefant

Tested on iOS and android, on iOS I also checked via a proxy if, when using `reachabilityUrl` option, googles servers are no longer contacted.

2023-07-03 04:54 UTC, jankapunkt requested changes
Please run `npm run lint` in order to fix the lint error. Apart from that it looks good to me

2023-07-03 04:54 UTC, jankapunkt commented on src/Meteor.js
> +      if (options.reachabilityUrl)
Please add brackets here.

2023-07-03 05:55 UTC, bratelefant commented on src/Meteor.js
> +      if (options.reachabilityUrl)
ok, guess I got it.

2023-07-03 20:30 UTC, TheRealNate approved these changes

2023-07-03 20:31 UTC, TheRealNate commented
Tentatively approved, but @jankapunkt's changes should be done first

2023-07-04 05:11 UTC, jankapunkt reviewed
Code looks good, I will run the network scan today to see if I can confirm the behavior, too. If confirmed I will approve / merge.

2023-07-04 10:00 UTC, merged

2023-07-04 10:01 UTC, jankapunkt commented
I will get a new release 2.5.1 out asap